### ISSUE TITLE
Create Big Brother Google Form 

### ISSUE THREAD

**Issue by internette** [jjm3x3/AmazingRaceFantasy#122]
As a league competitor, I would like to submit my lineup for Big Brother Season 26 via Google Form, similar to Amazing Race

**Comment by jjm3x3** [comment]
I just put this in the BB update milestone, but an argument could be made that it should instead go in a new milestone to support the season. Open to feedback on this.

**Comment by jjm3x3** [comment]
The details have been shared privately with me and emailed out to the parties that were looking to participate!
