### ISSUE TITLE
Create a Google Form for Contestant Team Ranking Submission

### ISSUE THREAD

**Issue by jjm3x3** [jjm3x3/AmazingRaceFantasy#38]
As suggested it may be easiest to start w/ just a google form for this since that way we don't have to do as much work with input validation and with user management and we can keep the data management to just a source code concern for now. Will see if the details of this form get posted.

**Comment by internette** [comment]
https://forms.gle/oHVGGQ2Now3hDLnw9

**Comment by jjm3x3** [comment]
Email has been scheduled with the details. Thanks for doing this!!
