### ISSUE TITLE
Use Wikipedia  Api

### ISSUE THREAD

**Issue by jjm3x3** [jjm3x3/AmazingRaceFantasy#5]
In order to avoid site breakages when the Wikipedia site changes we should switch to use the Wikipedia Api. Once this is completed all references to Jsdom should be removed (both the core lib and the types lib)

**Comment by jjm3x3** [comment]
So @CAnthonySiever this work was done to the best of your abilities it seems, but the stated goal in the issue was not really achieved. Even though it is a slight change up in the approach I am wondering if it makes sense to take any further conversation on this to #25 WDYT?

**Comment by CAnthonySiever** [comment]
I owe you something that gets the required section number from the Wikipedia API (I know this is possible but haven't had the time to commit to that, hopefully soon 🙏 ), that way we don't have to manually change the section number whenever it moves around, but I believe that will satisfy that. As it is currently, I agree it is only _slightly_ more reliable (if that) when looking to avoid site-breakages whenever the wiki is updated.
